version: '3.9'

services:
  postgres-compose:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=blog
    ports:
      - "4444:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
      
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "elielfranca90@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "55555:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge